### ISSUE TITLE
Submission: HTTP load generator function using Dockerfile template

### ISSUE THREAD

**Issue by kylos101** [openfaas/store#119]
Hello there,

Long time reader, second time writer! I'd like to submit a function to the store for [HEY](https://github.com/rakyll/hey).

I've been selfishly using this on my local cluster when demoing the power of Serverless to peers (using this function to load test other functions, showing how they scale, are async, etc.) and thought this might be good to share with folks, too.

This is my first real contribution to open source, aside from reporting issues. As time permits, may I ask you to let me know if this is approved, you'd like more info, or if this is rejected? I'd be happy to share a pull request for the store update if it is approved. 

References:
[The function source](https://github.com/kylos101/openfaas-hey)
[The function image repo](https://hub.docker.com/repository/docker/kylos101/openfaas-hey)
[The function store update](https://github.com/kylos101/store/tree/http-load-gen)

Take care,

Kyle

**Comment by alexellis** [comment]
Hi Kyle, I think `hey` could be interesting, if you want to add it as a sample function to the faas repo, then we will handle the build and publishing of the function, then you can submit a PR to the store.json file. How does that sound?

Alex

**Comment by kylos101** [comment]
Awesome, will do, I'll take a swing at it tonight!

**Comment by alexellis** [comment]
https://github.com/openfaas/faas/tree/master/sample-functions

**Comment by kylos101** [comment]
Thanks for the link.

To start, would it help if I created an issue in the faas repo as well?

**Comment by alexellis** [comment]
No need. Please start with the PR and optimise the dockerfile to use && between each run step for caching.

**Comment by kylos101** [comment]
[I started this PR for adding `hey` as a sample function.](https://github.com/openfaas/faas/pull/1489). Appreciate the tip Re: caching, too.
