### ISSUE TITLE
Submission Request - COBOL Template

### ISSUE THREAD

**Issue by devries** [openfaas/store#122]
I wrote a COBOL template, which is a bit tongue in cheek, but could be another potential addition to the store. It's currently in a fairly large container, and I may work on trimming in down a bit as we go forward. The build and deployment container is `devries/cobol:latest` which is just a `debian:buster-slim` container with GnuCOBOL installed. The Dockerfile I use to create that container is here: https://github.com/devries/docker-cobol/blob/master/Dockerfile

The template itself is located at https://github.com/devries/openfaas-cobol-template, and contains a README explaining how it is used. I would propose adding the following to the `templates.json` file:

```json
    {
        "template": "cobol",
        "platform": "x86_64",
        "language": "COBOL",
        "source": "devries",
        "description": "COBOL Template",
        "repo": "https://github.com/devries/openfaas-cobol-template",
        "official": "false"
    }
```

**Comment by alexellis** [comment]
Looks good to me, please feel free to send a PR, or if you have, reference it here 👍

**Comment by devries** [comment]
Thanks for accepting this! I will close the issue since the merge is complete.
