### ISSUE TITLE
preview outside OpenFaaS?

### ISSUE THREAD

**Issue by sknebel** [openfaas/store#13]
As a random visitor of this repository, it would be nice if I could easily view the functions in here. Right now it's not so bad to directly read the JSON file, but especially if this collection (hopefully) grows, it would be great to have a nicer view.

Maybe the code rendering the frontend in OpenFaaS could be used to create a simple page, e.g. on GitHub pages and linked from this repo?

**Comment by rorpage** [comment]
Derek add label: enhancement

**Comment by itscaro** [comment]
Something like this? https://github.com/itscaro/store/blob/json-md/store.md

**Comment by alexellis** [comment]
The table version looks pretty good 👍

**Comment by itscaro** [comment]
is it possible to give CI the write permission to Git repo?

**Comment by rgee0** [comment]
I'm going to close this due to the prolonged period of inactivity.  The idea has merit and I think that it could be considered alongside any strategic changes to the UI.

Please feel free to open a new issue if you are keen to work on this and perhaps engage with the UI channel on Slack.
