### ISSUE TITLE
I can only see two store functions.

### ISSUE THREAD

**Issue by VladoPortos** [openfaas/store#137]
I just deployed latest OpenFass on my kubernetes and when looking on Portal I can see only two store functions "NodeInfo" and "Sha512sum", do I need to update the list somehow as I can see more in the github json...

**Comment by alexellis** [comment]
Hi, that's to be expected if you're using 64-bit ARM, but if you want to use 32-bit ARM or a regular cloud computer (Intel), you'll see many more.

Just to let you know, we don't do technical support on GitHub, so I would encourage you to join Slack

https://slack.openfaas.io

**Comment by VladoPortos** [comment]
Thanks @alexellis makes sense, yes I'm on arm64

**Comment by alexellis** [comment]
You can build your own functions on your laptop with the publish command and may enjoy my Serverless ebook listed on https://openfaas.com too. 

I'll also have a think about adding more for arm64.

**Comment by VladoPortos** [comment]
@alexellis I know, the build of my own function works perfectly fine :) It just did not click to me that the store is based on architecture :) I'm running OpenFaas on my 9 node rpi4 kubernetes cluster, and basically learning OpenFaas on it. By the way thanks for all the articles about Kubernetes and OpenFaas on medium.com they were great read.

**Comment by alexellis** [comment]
Feel free to join us in the #home-clusters channel on OpenFaaS Slack to chat with the community and share more about what you'd like to see in the future.

https://slack.openfaas.io
