### ISSUE TITLE
nslookup function doesn't anymore deploy on arm

### ISSUE THREAD

**Issue by cipy** [openfaas/store#144]
```

$ faas-cli describe nslookup
Name:                nslookup
Status:              Not Ready
Replicas:            1
Available replicas:  0
Invocations:         0
Image:               jockdarock/nslookup-arm-faas:latest-armhf
Function process:    
URL:                 http://127.0.0.1:8080/function/nslookup
Async URL:           http://127.0.0.1:8080/async-function/nslookup
Labels:              faas_function : nslookup
Annotations:         prometheus.io.scrape : false

$ faas-cli logs nslookup
2021-08-16T20:41:09+03:00 2021/08/16 17:41:09 Writing lock-file to: /tmp/.lock

**Comment by alexellis** [comment]
Hi @cipy perhaps you can contribute nslookup to the official store repo then?

Jock's image will be really outdated at this point

https://github.com/openfaas/store-functions

The store builds all images as multi-arch, feel free to follow one of the existing examples.

Alex

**Comment by alexellis** [comment]
I've added it for you:

https://github.com/openfaas/store-functions/commit/8232a7a8128e8d6bebde917c7445da5d0795e526

Please consider becoming a project sponsor if you're not one already: https://github.com/sponsors/openfaas
