### ISSUE TITLE
Remove network attributes from store.json & store-armhf.json files

### ISSUE THREAD

**Issue by rgee0** [openfaas/store#27]
With the changes implemented in https://github.com/openfaas/faas-swarm/commit/e36f90b36f5b81498ea7dc018b3cf0b48127f7a1 the network attribute can be ascertained by the swarm backend.

This issue is to remove the network values from the store.json & store-armhf.json files

**Comment by rgee0** [comment]
Tightened the scope as arm64 doesnt appear to have the network label yet

**Comment by alexellis** [comment]
Please raise a PR when ready.
