### ISSUE TITLE
OpenFaaS function for Pigo face detector

### ISSUE THREAD

**Issue by esimov** [openfaas/store#37]
Here is an OpenFaaS function to detect faces using the Pigo face detection library. https://github.com/esimov/pigo-openfaas

**Comment by ivanayov** [comment]
Thanks @esimov 

Can you please open a PR?

Could you also compare the results by time/accuracy with https://github.com/openfaas/store/blob/master/store.json#L44 ?
We may keep both or if yours is faster, remove the other one.

Ivana

**Comment by esimov** [comment]
Hey @ivanayov I just sent a PR, however i just committed without to Signed-off. If you cannot accept it, i can make another PR.

Thank you,
Endre

**Comment by ivanayov** [comment]
Derek close

**Comment by alexellis** [comment]
For future reference there is no need to create a new PR. You can amend commits using the links in the contribution guide.

**Comment by esimov** [comment]
Thanks Alex, i'll do so.

**Comment by alexellis** [comment]
Very nice @esimov, I just tested the function and it worked well 👍 🎉 

Do you also have the JSON mode available which gives back the co-ordinates of the faces detected?

**Comment by esimov** [comment]
@alexellis yes, the response should return the coordinates of the detected faces, however the function handler does not show the json result in the response body.

```go
j, err := json.Marshal(resp)
if err != nil {
	return fmt.Sprintf("Error encoding output: %s", err)
}

// Return face rectangle coordinates
return string(j)
```
