### ISSUE TITLE
Update README about template store

### ISSUE THREAD

**Issue by alexellis** [openfaas/store#46]
We need to update the README with some docs / headings about the template store and how it works / how to submit.

**Comment by martindekov** [comment]
https://github.com/openfaas/docs/pull/93 is opened I can add the same info + some additional on how to submit

**Comment by martindekov** [comment]
I will soon open PR for this along with adding [templates table](https://github.com/openfaas/templates/issues/100)

**Comment by rgee0** [comment]
I'm going to close this as the information exists since https://github.com/openfaas/store/commit/884393529d8121f8d6dfd168f817f0315070373a which this issue pre-dates.  Suggest that closure keyword was missed from the PR https://github.com/openfaas/store/pull/69
