### ISSUE TITLE
Crystal template

### ISSUE THREAD

**Issue by TPei** [openfaas/store#49]
I'd like to add the crystal template to the template store:
- Template: https://github.com/TPei/crystal_openfaas

It was already added to the community.md in https://github.com/openfaas/faas/pull/941

I could open a PR with: https://github.com/TPei/store/commit/a9c644121034217b3bfb88cfe6261606df829cd2

**Comment by TPei** [comment]
I opened https://github.com/openfaas/store/pull/50

**Comment by kingdonb** [comment]
#50 was merged and Crystal is in the faas-cli store, do you want to close this issue?

```
$ faas-cli template store pull crystal
Fetch templates from repository: https://github.com/tpei/crystal_openfaas at master
2020/08/30 21:25:26 Attempting to expand templates from https://github.com/tpei/crystal_openfaas
2020/08/30 21:25:27 Fetched 1 template(s) : [crystal] from https://github.com/tpei/crystal_openfaas
```

Thanks for this!

**Comment by TPei** [comment]
Ehm, sure, thanks for pointing this out :)
