### ISSUE TITLE
Add support for PUT, PATCH, and DELETE methods for HTTP templates

### ISSUE THREAD

**Issue by kturcios** [openfaas/store#61]
This will only apply to the templates that are based upon of-watchdog.

**Comment by rgee0** [comment]
@kturcios is this in the correct repo?  If so, can you provide an example the kind of change you're proposing, please?

**Comment by kturcios** [comment]
@rgee0 Yeah I opened it up here because of this comment from @alexellis 
https://github.com/openfaas-incubator/node8-express-template/pull/17#issuecomment-460667265
