### ISSUE TITLE
Submission request - Perl template

### ISSUE THREAD

**Issue by tmiklas** [openfaas/store#81]
I would like to suggest adding Perl template to the official store.

Currently the Alpine version is working correctly hence suggestion to call it `perl-alpine`, to avoid collision with currently (not fully working) template found in incubator.

My template is located at https://github.com/tmiklas/openfaas-perl-templates, usage described in README.

Proposed `templates.json` bit:
```
    {
        "template": "perl-alpine",
        "platform": "x86_64",
        "language": "Perl",
        "source": "tmiklas",
        "description": "Perl language template based on Alpine image",
        "repo": "https://github.com/tmiklas/openfaas-perl-templates",
        "official": "false"
    }
```

**Comment by alexellis** [comment]
Please go ahead and send your PR

**Comment by alexellis** [comment]
Change: `Perl` -> `perl` for the `language` field.

**Comment by tmiklas** [comment]
PR merged into master, closing as completed/resolved - thank you!
