### ISSUE TITLE
Allow custom env-vars

### ISSUE THREAD

**Issue by alexellis** [openfaas/store#9]
We need to allow custom env-vars so that things like `read_timeout` can be set with good defaults for the ML examples like the inception function. cc/ @ericstoekl @kenfdev

**Comment by stefanprodan** [comment]
I think we need to show a HTML form that will render a textbox for each env var with a default value if it's present in the json file.

The sore definition could looks like this:

```json
{
  "icon": "https://raw.githubusercontent.com/stefanprodan/openfaas-promq/master/logo.png",
  "title": "Prometheus query runner",
  "description": "Runs PromQL for a given Prometheus server",
  "image": "stefanprodan/openfaas-promq",
  "name": "promq",
  "network": "func_functions",
  "repo_url": "https://github.com/stefanprodan/openfaas-promq",
  "environment": {
    "PROMETHEUS_URL": "http://prometheus:9090",
    "FORMAT": "table"
  }
}
```

**Comment by kenfdev** [comment]
How about an edit (like) button which sends you to the "manually deploy" tab with information filled in for the function.
And adding Env Vars dynamic input to the "manually deploy" tab.
Wish I could create a simple prototype but not have enough time atm.

In addition, we're trying to add a url button for the `repo_url` , too. So the UI will start to get complicated...
Maybe a context menu toggle? (Not sure if it works well with Material Design & Cross Browser)

@stefanprodan You're definition LGTM.

**Comment by ivanayov** [comment]
@alexellis this is now available. Can I close the issue?

**Comment by alexellis** [comment]
Sure
