### ISSUE TITLE
Submission Request - Elixir Templates

### ISSUE THREAD

**Issue by dokie** [openfaas/store#96]
I'd like to submit our Elixir templates for the Classic watchdog and the new HTTP `of-watchdog` which are [here](https://github.com/arboricity/openfaas-templates).

They both use Elixir v1.9+ and the HTTP template makes use of [Cowboy](https://github.com/ninenines/cowboy) and [Plug](https://github.com/elixir-plug/plug).

**Comment by alexellis** [comment]
Congrats one getting this working Mike.

I wonder if `openfaas_endpoint.ex` may be called `handler.ex`?

Is the `plug` suffix adding anything given that there's no `elixir-http` yet, it could be more succinct without the framework in the name.

* The template looks more like a webserver than a function, so would `elixir-service` or `elixir-service-http` work too?

* How do users manage dependencies, should they have them? I.e. what's the equivalent of npm, pip and Nuget?

* Could you populate the README.md in your repo with some examples of usage? i.e. https://github.com/openfaas-incubator/node10-express-service/ and https://github.com/openfaas-incubator/golang-http-template/issues/31

**Comment by dokie** [comment]
Thanks Alex. I will work on the suggested changes and comment back here when completed.

**Comment by alexellis** [comment]
Is `openfaas_endpoint.ex` a name that is required by Elixir?

**Comment by dokie** [comment]
No the Elixir requirements are more to do with code repo layout not naming of files.

**Comment by dokie** [comment]
@alexellis I have updated the code files and tested it locally under the `of_watchdog` go program. I am a bit confused / torn between what to do next with it. The dependencies are all stated explicitly in the `mix.lock` file and the Dockerfile will build the example with the layout here after running
```
faas-cli new --lang elixir-service hello-elixir-service
faas-cli build -f ./hello-elixir-service.yml
```
However, if an Elixir developer wanted to build their service and test it locally, they would need an Elixir compatible mix project created from the files in the template for them to run the standard Elixir build process `mix compile` for example. So that's the part I have a block with - how should I (or even, should I at all) somehow include a way for that to happen (shell script perhaps?) and then of course that can be documented.

I guess I am looking for some best-practise advise from the OpenFaaS perspective.
